project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LogIn.as_view(), name='log_in'),
    path('logout/', views.LogOut.as_view(), name='log_out'),
    path('change_password/', views.PasswordChange.as_view(), name='change_password'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit', views.UpdateProfile.as_view(), name='update_profile'),
    path('registration/', views.Registration.as_view(), name='registration'),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('site/', include('core_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('market_app.urls')),
    path('api/', include('market_app.api.urls', namespace="market-api")),
]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

project/accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from .validators import phone_number_validate, birthday_validate, avatar_format_validate, \
    avatar_dimensions_validate


MAX_AVATAR_SIZE = 100 * 1024
GENDERS_CHOICES = [
    ('m', _('Male')),
    ('f', _('Female')),
]


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        verbose_name=_('user'),
        on_delete=models.CASCADE,
        related_name='profile')

    first_name = models.CharField(
        verbose_name=_('first name'),
        max_length=150,
        blank=True)

    last_name = models.CharField(
        verbose_name=_('last name'),
        max_length=150,
        blank=True)

    phone_number = models.CharField(
        verbose_name=_('phone number'),
        blank=True,
        default='',
        max_length=16,
        validators=[phone_number_validate])

    birthdate = models.DateField(
        verbose_name=_('birthdate'),
        validators=[birthday_validate],
        null=True)

    country = models.CharField(
        verbose_name=_('country'),
        blank=True,
        max_length=127)

    town = models.CharField(
        verbose_name=_('town'),
        blank=True,
        max_length=127)

    about_user = models.TextField(
        verbose_name=_('about user'),
        blank=True,
        max_length=1024)

    avatar = models.ImageField(
        max_length=MAX_AVATAR_SIZE,
        verbose_name=_('avatar'),
        upload_to='avatars/',
        null=True,
        blank=True,
        # default='avatars/default_user_avatar.jpg',
        validators=[avatar_format_validate, avatar_dimensions_validate]
    )

    gender = models.CharField(
        verbose_name=_('gender'),
        max_length=3,
        choices=GENDERS_CHOICES,
        blank=True,
    )

    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')

    def __str__(self):
        return f'Profile: {self.user.username}'

    def get_public_information(self) -> dict:
        public_information = {
            _('with us since'): self.user.date_joined,
            _('birthdate'): self.birthdate,
            _('first name'): self.first_name,
            _('last name'): self.last_name,
            _('gender'): self.gender,
            _('phone number'): self.phone_number,
            _('country'): self.country,
            _('town'): self.town,
            _('about user'): self.about_user,
        }
        return public_information


@receiver(signal=post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    """Create or update the user's profile if the user-object is saved"""
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from .models import Profile
from .validators import birthday_validate


class MyDateInput(forms.DateInput):
    input_type = 'date'


class RegistrationForm(UserCreationForm):
    """
    A form that creates a user, with no privileges, from the given username, email and
    password.
    """
    email = forms.EmailField()
    field_order = ['username', 'password']

    birthdate = forms.DateField(
        label=_('Birthdate'),
        required=True,
        widget=MyDateInput(),
        localize=True,
        validators=[birthday_validate]
    )

    def save(self, commit=True):
        user: User = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        user.profile.birthdate = self.cleaned_data['birthdate']
        return user


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user', 'birthdate']

    first_name = forms.CharField(label=_('Name'), max_length=31, required=False)
    last_name = forms.CharField(label=_('Surname'), max_length=31, required=False)
    avatar = forms.FileField(label=_('Avatar'), required=False)
    field_order = ['first_name', 'last_name']

    def save(self, commit=True):
        user: User = self.instance.user
        user_data = {
            'first_name': self.cleaned_data['first_name'],
            'last_name': self.cleaned_data['last_name']
        }
        User.objects.filter(id=user.id).update(**user_data)
        return super(ProfileUpdateForm, self).save()

project/accounts/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView, UpdateView, DetailView

from .forms import *


class LogIn(LoginView):
    template_name = 'accounts/log_in_template.html'
    redirect_authenticated_user = True


class LogOut(LogoutView):
    template_name = 'accounts/log_out_page.html'


class ProfileView(LoginRequiredMixin, DetailView):
    template_name = 'accounts/profile.html'
    model = Profile
    context_object_name = 'profile'

    def get_object(self, queryset=None):
        return self.request.user.profile


class UpdateProfile(LoginRequiredMixin, UpdateView):
    """View for updating user profile, with a response rendered by a template."""
    model = ProfileView
    form_class = ProfileUpdateForm
    template_name = 'accounts/update_profile.html'
    success_url = reverse_lazy('accounts:profile')

    def get_object(self, queryset=None):
        return self.request.user.profile


class Registration(FormView):
    """
    View for register and log in a new user,
    with a redirect the user to his profile page after success registration.
    """
    template_name = 'accounts/registration.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        user = form.save()
        login(self.request, user=user)
        return super(Registration, self).form_valid(form=form)


class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    template_name = 'accounts/password_change_template.html'
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        messages.success(self.request, _('Your password was changed.'))
        return super(PasswordChange, self).form_valid(form=form)

project/accounts/templates/accounts/app_base.html
{% extends 'core_app/base_template.html' %}
{% load i18n %}

{% block main_left_block %}
  {% include 'accounts/include/current_user_card.html' with user=user %}
  {% block main_left_card %}
  {% endblock %}
{% endblock %}

project/accounts/templates/accounts/info_view.html
{% extends 'accounts/app_base.html' %}
{% load i18n %}
{% block main_center_card %}
  <h1 class="card-header content-title">
    {{ title }}
  </h1>
  <div class="card-body">
  <p>
    {{ message }}
  </p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <a href="/">
        {% trans 'Go to main page' %}
      </a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'accounts:profile' %}">
        {% trans 'Profile' %}
      </a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'accounts:log_out' %}">
        {% trans 'Log out' %}
      </a>
    </li>
  </ul>
{% endblock %}

project/accounts/templates/accounts/log_in_template.html
{% extends 'core_app/form_page.html' %}
{% load i18n %}

{% block page_title %}
  {% trans 'Log in' %}
{% endblock %}


{% block form_block %}
  <form method="post"
        action="{% url 'accounts:log_in' %}">
    {% csrf_token %}
    {% include 'core_app/include/pretty_form.html' with form=form %}
    <hr class="my-4">
    <a href="{% url 'accounts:registration' %}"
       class="link-secondary">
      <p class="text-center">
        {% trans "I don't have an account" %}
      </p>
    </a>
  </form>
{% endblock %}

project/accounts/templates/accounts/log_out_page.html
{% extends 'accounts/app_base.html' %}
{% load i18n %}
{% block main_center_card %}
  <h1 class="card-header content-title">
    {% trans 'You have been logged out' %}
  </h1>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <a href="/">
        {% trans 'Go to main page' %}
      </a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
    </li>
    <li class="list-group-item">
      <a href="{% url 'accounts:registration' %}">
        {% trans 'Create an account' %}
      </a>
    </li>
  </ul>
{% endblock %}

project/accounts/templates/accounts/password_change_template.html
{% extends 'core_app/form_page.html' %}
{% load i18n %}

{% block page_title %}
  {% trans 'Change password' %}
{% endblock %}

{% block form_block %}
  <form method="post" action="{% url 'accounts:change_password' %}">
    {% csrf_token %}
    {% include 'core_app/include/pretty_form.html' %}
  </form>
{% endblock %}

project/accounts/templates/accounts/profile.html
{% extends 'accounts/app_base.html' %}
{% load i18n %}

{% block main_center_card %}
  <h1 class="card-header content-title">
    {% trans 'Profile' %}: {{ user.username }}
  </h1>

  <div class="list-group list-group-flush">
    {% for label, value in profile.get_public_information.items %}
    {% if value %}
      <li class="list-group-item">
        <div class="row">
          <div class="col-md-3">

            <b>{{ label|capfirst }}</b>:
          </div>
          <div class="col-md-9">
            {{ value }}

          </div>
        </div>
      </li>
    {% endif %}
  {% endfor %}
  </div>

{% endblock %}

project/accounts/templates/accounts/registration.html
{% extends 'accounts/app_base.html' %}
{% load i18n %}

{% block main_center_card %}
  <h1 class="card-header content-title">
    {% trans 'Registration' %}
  </h1>
  <div class="card-body">
    <form method="post" action="{% url 'accounts:registration' %}">
      {% csrf_token %}
      {% include 'core_app/include/pretty_form.html' with form=form %}
    </form>
  </div>

{% endblock %}

project/accounts/templates/accounts/update_profile.html
{% extends 'accounts/app_base.html' %}
{% load i18n %}

{% block main_center_card %}
  <h1 class="card-header content-title">
    {% trans 'Edit my profile.' %}
  </h1>
  <div class="m-2">
    <form method="post" enctype="multipart/form-data" action="{% url 'accounts:update_profile' %}">
      {% csrf_token %}
      {% include 'core_app/include/pretty_form.html' with without_button=True %}
      <div class="btn-container d-flex justify-content-center flex-wrap">
        <button class="btn btn-primary m-1" type="submit">
          {% trans 'Submit' %}
        </button>
        <a class="btn btn-primary m-1" href="{% url 'accounts:change_password' %}">
          {% trans 'Change password' %}
        </a>
      </div>
    </form>
  </div>
{% endblock %}
{% block main_left_block %}
{% endblock %}