project/market_app/api/urls.py
from rest_framework.routers import DefaultRouter

from market_app.api.views import (
    ProductViewSet, MarketViewSet, ProductTypeViewSet,
    ProductCategoryViewSet, OrderViewSet, OrderItemViewSet, OperationViewSet,
    BalanceViewSet, CartViewSet, CouponViewSet, UserViewSet,
)

app_name = "market-api"

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("markets", MarketViewSet)
router.register("product-categories", ProductCategoryViewSet)
router.register("product-types", ProductTypeViewSet)
router.register("order-items", OrderItemViewSet)
router.register("operations", OperationViewSet)
router.register("balances", BalanceViewSet)
router.register("coupons", CouponViewSet)
router.register("orders", OrderViewSet)
router.register("users", UserViewSet)
router.register("carts", CartViewSet)

urlpatterns = router.urls

project/market_app/urls.py
from django.urls import path
from . import views

app_name = 'market_app'
urlpatterns = [
    path('product/<int:pk>', views.ProductView.as_view(), name='product'),
    path('', views.CatalogueView.as_view(), name='catalogue'),
    path('create_product/', views.ProductCreateView.as_view(), name='create_product'),
    path('edit_product/<int:pk>', views.ProductEditView.as_view(), name='edit_product'),
    path('create_type/product/<int:pk>', views.ProductTypeCreate.as_view(), name='create_type'),
    path('edit_type/<int:pk>', views.ProductTypeEdit.as_view(), name='edit_type'),
    path('create_market/', views.MarketCreateView.as_view(), name='create_market'),
    path('edit_market/<int:pk>', views.MarketEditView.as_view(), name='edit_market'),
    path('my_cart/', views.CartView.as_view(), name='cart'),
    path('market/shipping/<int:pk>', views.ShippingPage.as_view(), name='shipping'),
    path('markets/', views.MarketsList.as_view(), name='market_list'),
    path('my_market/', views.UserMarketView.as_view(), name='user_market'),
    path('market/<int:pk>', views.MarketView.as_view(), name='market'),
    path('check_out/<int:pk>', views.CheckOutView.as_view(), name='checkout'),
    path('top_up', views.TopUpView.as_view(), name='top_up'),
    path('paying/<int:pk>', views.PayingView.as_view(), name='paying'),
    path('order_confirmation/', views.OrderConfirmationView.as_view(), name='order_confirmation'),
    path('search/', views.SearchProducts.as_view(), name='search_products'),
    path('operations/', views.OperationHistoryView.as_view(), name='operation_history'),
    path('order/<int:pk>', views.OrderDetail.as_view(), name='order_detail'),
    path('order/cancel/<int:pk>', views.cancel_order_view, name='order_cancel'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('coupons/my', views.UserCouponListView.as_view(), name='user_coupons')
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('site/', include('core_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('market_app.urls')),
    path('api/', include('market_app.api.urls', namespace="market-api")),
]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

project/market_app/api/views.py
from rest_framework import viewsets

from market_app.api.serializers import *


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.filter().order_by()
    serializer_class = ProductSerializer


class MarketViewSet(viewsets.ModelViewSet):
    queryset = Market.objects.all().order_by("-created_at")
    serializer_class = MarketSerializer


class ProductTypeViewSet(viewsets.ModelViewSet):
    queryset = ProductType.objects.filter().order_by()
    serializer_class = ProductTypeSerializer


class ProductCategoryViewSet(viewsets.ModelViewSet):
    queryset = ProductCategory.objects.filter().order_by()
    serializer_class = ProductCategorySerializer


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.filter().order_by()
    serializer_class = OrderSerializer


class OrderItemViewSet(viewsets.ModelViewSet):
    queryset = OrderItem.objects.filter().order_by()
    serializer_class = OrderItemSerializer


class OperationViewSet(viewsets.ModelViewSet):
    queryset = Operation.objects.filter().order_by()
    serializer_class = OperationSerializer


class BalanceViewSet(viewsets.ModelViewSet):
    queryset = Balance.objects.filter().order_by()
    serializer_class = BalanceSerializer


class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.filter().order_by()
    serializer_class = CartSerializer


class CouponViewSet(viewsets.ModelViewSet):
    queryset = Coupon.objects.filter().order_by()
    serializer_class = CouponSerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.filter().order_by()
    serializer_class = UserSerializer

project/market_app/views.py
import json
import re

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.contrib.auth.views import redirect_to_login
from django.core.exceptions import PermissionDenied
from django.db.models import Q, Prefetch
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import generic

from currencies.models import Currency
from currencies.services import get_currency_code_by_language, DEFAULT_CURRENCY_CODE, \
    get_exchanger
from .forms import ProductForm, MarketForm, ProductUpdateForm, AddToCartForm, ProductTypeForm, CreditCardForm, \
    AdvancedSearchForm, CartForm, CheckOutForm, TopUpForm, AgreementForm
from .models import Product, Market, ProductType, Operation, Order, OrderItem, Coupon, Cart
from .services import top_up_balance, make_purchase, prepare_order, \
    get_products


class MarketOwnerRequiredMixin(PermissionRequiredMixin):
    def get_permission_denied_message(self):
        return self.permission_denied_message or "Current user isn't the market owner"

    def has_permission(self):
        is_current_user_the_market_owner = getattr(
            self, 'request').user.id == self.get_current_market_owner_id()
        if self.permission_required is None:
            return is_current_user_the_market_owner
        return super(MarketOwnerRequiredMixin, self).has_permission() and is_current_user_the_market_owner

    def get_current_market_owner_id(self):
        raise NotImplementedError("""Method get_current_market_owner_id hasn't been implemented yet.""")


class ProductEditView(MarketOwnerRequiredMixin, generic.UpdateView):
    form_class = ProductUpdateForm
    model = Product
    context_object_name = 'product'
    template_name = 'market_app/edit_product.html'

    def get_success_url(self):
        return reverse_lazy('market_app:product', args=[self.object.pk])

    def get_current_market_owner_id(self):
        return Product.objects.filter(pk=self.kwargs['pk']).values_list('market__owner_id', flat=True)[0]


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = ProductForm
    template_name = 'market_app/create_product.html'

    def form_valid(self, form):
        product = form.save(commit=False)
        product.market = self.request.user.market
        product.save()
        return HttpResponseRedirect(product.get_absolute_url())


class ProductTypeCreate(MarketOwnerRequiredMixin, generic.CreateView):
    model = ProductType
    form_class = ProductTypeForm
    template_name = 'market_app/product_type_create.html'

    def get_current_market_owner_id(self):
        return Product.objects.filter(pk=self.kwargs['pk']).values_list('market__owner_id', flat=True)[0]

    def get_success_url(self):
        return reverse_lazy('market_app:product', args=[self.kwargs['pk']])

    def get_form_kwargs(self):
        kwargs = super(ProductTypeCreate, self).get_form_kwargs()
        kwargs['product'] = Product.objects.get(pk=self.kwargs['pk'])
        return kwargs


class ProductTypeEdit(MarketOwnerRequiredMixin, generic.UpdateView):
    model = ProductType
    form_class = ProductTypeForm
    template_name = 'market_app/product_type_edit.html'

    def get_form_kwargs(self):
        kwargs = super(ProductTypeEdit, self).get_form_kwargs()
        kwargs['product'] = self.object.product
        kwargs['product_type'] = self.object
        return kwargs

    def get_success_url(self):
        return self.get_object().product.get_absolute_url()

    def get_current_market_owner_id(self):
        return ProductType.objects.filter(pk=self.kwargs['pk']).values_list('product__market__owner_id', flat=True)[0]


class CatalogueView(generic.ListView):
    template_name = 'market_app/catalogue.html'
    context_object_name = 'products'

    def get_queryset(self):
        return get_products()


class ProductView(generic.FormView):
    model = Product
    template_name = 'market_app/product.html'
    form_class = AddToCartForm
    success_url = reverse_lazy('market_app:catalogue')

    def setup(self, request, *args, **kwargs):
        super(ProductView, self).setup(request, *args, **kwargs)
        self.object = Product.objects.prefetch_related(
            Prefetch('product_types', ProductType.objects.filter(units_count__gt=0))
        ).select_related('market').get(pk=self.kwargs['pk'])
        self.product_types = self.object.product_types.all()

    def get_context_data(self, **kwargs):
        context = super(ProductView, self).get_context_data(**kwargs)
        context['product'] = self.object
        context['products'] = get_products().filter(category_id=self.object.category_id)
        context['markup_percents'] = json.dumps(
            {i_type.pk: str(i_type.markup_percent) for i_type in self.product_types}
        )
        context['has_types'] = bool(self.product_types)
        context['is_market_owner'] = self.object.market.owner_id == self.request.user.id
        return context

    def get_form_kwargs(self):
        kwargs = super(ProductView, self).get_form_kwargs()
        kwargs['types'] = self.product_types
        return kwargs

    def post(self, request, *args, **kwargs):
        return super(ProductView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        if not self.request.user.is_authenticated:
            return redirect_to_login(next=self.object.get_absolute_url())
        quantity = form.cleaned_data['quantity']
        if self.object.market.owner_id == self.request.user.id:
            form.add_error('product_type', _('Cannot buy your own product.'))
            return super(ProductView, self).form_invalid(form)
        self.request.user.cart.set_item(
            product_type_pk=form.cleaned_data['product_type'],
            quantity=quantity)
        return super(ProductView, self).form_valid(form)


class MarketCreateView(LoginRequiredMixin, generic.CreateView):
    template_name = 'market_app/market_create.html'
    form_class = MarketForm
    success_url = reverse_lazy('market_app:user_market')

    def setup(self, request, *args, **kwargs):
        super(MarketCreateView, self).setup(request, *args, **kwargs)
        self.has_market = Market.objects.filter(owner_id=request.user.id).exists()

    def get(self, request, *args, **kwargs):
        if self.has_market:
            return HttpResponseRedirect(reverse_lazy('market_app:user_market'), status=302)
        return super(MarketCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if self.has_market:
            raise PermissionDenied('User can have only one market')
        return super(MarketCreateView, self).post(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(MarketCreateView, self).get_form_kwargs()
        kwargs['owner'] = self.request.user
        return kwargs


class MarketEditView(MarketOwnerRequiredMixin, generic.UpdateView):
    model = Market
    fields = ['name', 'description', 'logo']
    template_name = 'market_app/market_edit.html'

    def get_success_url(self):
        return self.object.get_absolute_url()

    def get_object(self, queryset=None):
        if not hasattr(self, 'object'):
            self.object = get_object_or_404(self.model, pk=self.kwargs['pk'])
        return self.object

    def get_current_market_owner_id(self):
        return self.get_object().owner_id


class CartView(LoginRequiredMixin, generic.FormView):
    template_name = 'market_app/cart_page.html'
    form_class = CartForm

    @property
    def cart(self) -> Cart:
        if not hasattr(self, '_cart'):
            cart = self.request.user.cart
            cart.prepare_items()
            self._cart = cart
        return self._cart

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context['cart'] = self.cart
        if not self.cart.is_filled:
            context["products"] = get_products()
        return context

    def get_form_kwargs(self):
        kwargs = super(CartView, self).get_form_kwargs()
        kwargs['cart'] = self.cart
        return kwargs

    def form_valid(self, form):
        if unpaid_order := Order.objects.filter(user=self.request.user, operation__isnull=True).first():
            message = _('Sorry, but you can not create a new order because you have an unpaid order. '
                        'Please pay for this unpaid order or cancel it')
            messages.warning(self.request, message)
            return HttpResponseRedirect(unpaid_order.get_absolute_url(), status=302)
        self.cart.items = form.cleaned_data
        order: Order = prepare_order(self.cart)
        almost_sold_types_pks = {
            item.product_type_id: item.amount for item in order.items.all() if
            item.amount < form.cleaned_data.get(str(item.product_type_id))
        }
        if almost_sold_types_pks:
            types = ProductType.objects.filter(
                id__in=almost_sold_types_pks).select_related('product').only('product__name')
            for product_type in types:
                amount = almost_sold_types_pks[product_type.pk]
                message = _('Sorry, product "{}" is almost sold out and we can sell only {} of these.')
                messages.warning(self.request, message.format(product_type.product.name, amount))
        return HttpResponseRedirect(reverse_lazy('market_app:checkout', kwargs={'pk': order.pk}))


class OrderDetail(PermissionRequiredMixin, generic.DetailView):
    template_name = 'market_app/order_detail.html'
    model = Order
    context_object_name = 'order'

    def get_context_data(self, **kwargs):
        context = super(OrderDetail, self).get_context_data(**kwargs)

project/market_app/templates/market_app/include/catalogue.html
{% load i18n %}
{% load currencies %}

<div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 g-2 m-0">
  {% for product in products %}
    <div class="col">
      <a class="text-decoration-none text-dark" href="{{ product.get_absolute_url }}">

        <div class="card h-100">
          <img class="card-img-top" style="object-fit: cover; height: 100%"
               src="{{ product.get_img_url }}" alt="product image">
          <p class="text-center">
            {{ product }}
          </p>
          <div class="p-1">
            <div style="text-align: right">
              {% if product.discount_percent %}
                <s>{% to_local_currency product.original_price %}</s> <br>
                <b class="text-success">{% to_local_currency product.sale_price %}</b>
              {% else %}
                <br>
                <b>{% to_local_currency product.original_price %}</b>
              {% endif %}
            </div>
          </div>
        </div>
      </a>

    </div>
  {% empty %}
    {% if display_text_when_no_products %}
      <div class="w-100">
        <div class="display-5 text-center">
          {% trans 'There are no products' %}.
        </div>
      </div>
    {% endif %}
  {% endfor %}
</div>

{% include 'market_app/include/paginator.html' %}

project/market_app/templates/market_app/include/paginator.html
{% load market_app_utils %}

{% if is_paginated %}
  <div class="paginator">
    <ul class="pagination justify-content-center my-2">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace 'page' 1 %}">
            <span aria-hidden="true">&laquo;&laquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?{% url_replace 'page' page_obj.previous_page_number %}">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      <li class="page-item">
        <span class="page-link" aria-hidden="true">{{ page_obj.number }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?{% url_replace 'page' page_obj.next_page_number %}">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?{% url_replace 'page' page_obj.paginator.num_pages %}">
            <span aria-hidden="true">&raquo;&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endif %}

project/market_app/templates/market_app/include/search.html
{% load static %}
{% load i18n %}
<form action="{% url 'market_app:search_products' %}">
  <div class="input-group my-2">
    <input type="search" class="form-control"
           name="q"
           placeholder="{% trans 'Search' %}"/>
    <button type="submit" class="btn btn-dark">
      <i class="bi bi-search"></i>
    </button>
  </div>
</form>

project/market_app/templates/market_app/include/side_nav.html
{% load i18n %}
{% load currencies %}
{% load cache %}

{% cache 60 side_nav CURRENT_LANGUAGE request.user.username %}
  <div class="card my-2 border-0">
    <div class="card-header content-title">
      {% trans 'Navigation' %}
    </div>
    <ul class="list-group list-group-flush text-center">
      <li class="list-group-item">
        <a href="{% url 'market_app:cart' %}">
          {% trans 'My cart' %}
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'market_app:orders' %}">
          {% trans 'My orders' %}
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'market_app:market_list' %}">
          {% trans 'Markets' %}
        </a>
      </li>
      <li class="list-group-item">
        <a href="{% url 'market_app:user_market' %}">
          {% trans 'My market' %}
        </a>
      </li>
      {% if user.is_authenticated %}
        <li class="list-group-item">
          <a href="{% url 'market_app:user_coupons' %}">
            {% trans 'Coupons' %}
          </a>
        </li>
        <li class="list-group-item">
          <a href="{% url 'market_app:operation_history' %}">
            {% trans 'Balance' %} {% to_local_currency user.balance.amount %}
          </a>
        </li>
      {% endif %}
    </ul>
  </div>
{% endcache %}