project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LogIn.as_view(), name='log_in'),
    path('logout/', views.LogOut.as_view(), name='log_out'),
    path('change_password/', views.PasswordChange.as_view(), name='change_password'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit', views.UpdateProfile.as_view(), name='update_profile'),
    path('registration/', views.Registration.as_view(), name='registration'),
]

project/core_app/urls.py
from django.urls import path
from . import views

app_name = 'core_app'

urlpatterns = [
    path('about_us', views.AboutUsView.as_view(), name='about_us')
]

project/market_app/urls.py
from django.urls import path
from . import views

app_name = 'market_app'
urlpatterns = [
    path('product/<int:pk>', views.ProductView.as_view(), name='product'),
    path('', views.CatalogueView.as_view(), name='catalogue'),
    path('create_product/', views.ProductCreateView.as_view(), name='create_product'),
    path('edit_product/<int:pk>', views.ProductEditView.as_view(), name='edit_product'),
    path('create_type/product/<int:pk>', views.ProductTypeCreate.as_view(), name='create_type'),
    path('edit_type/<int:pk>', views.ProductTypeEdit.as_view(), name='edit_type'),
    path('create_market/', views.MarketCreateView.as_view(), name='create_market'),
    path('edit_market/<int:pk>', views.MarketEditView.as_view(), name='edit_market'),
    path('my_cart/', views.CartView.as_view(), name='cart'),
    path('market/shipping/<int:pk>', views.ShippingPage.as_view(), name='shipping'),
    path('markets/', views.MarketsList.as_view(), name='market_list'),
    path('my_market/', views.UserMarketView.as_view(), name='user_market'),
    path('market/<int:pk>', views.MarketView.as_view(), name='market'),
    path('check_out/<int:pk>', views.CheckOutView.as_view(), name='checkout'),
    path('top_up', views.TopUpView.as_view(), name='top_up'),
    path('paying/<int:pk>', views.PayingView.as_view(), name='paying'),
    path('order_confirmation/', views.OrderConfirmationView.as_view(), name='order_confirmation'),
    path('search/', views.SearchProducts.as_view(), name='search_products'),
    path('operations/', views.OperationHistoryView.as_view(), name='operation_history'),
    path('order/<int:pk>', views.OrderDetail.as_view(), name='order_detail'),
    path('order/cancel/<int:pk>', views.cancel_order_view, name='order_cancel'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('coupons/my', views.UserCouponListView.as_view(), name='user_coupons')
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('site/', include('core_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('market_app.urls')),
    path('api/', include('market_app.api.urls', namespace="market-api")),
]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

project/core_app/models.py
from django.db import models

# Create your models here.

project/core_app/views.py
from django.views.generic import TemplateView


class AboutUsView(TemplateView):
    template_name = 'core_app/about_us_template.html'

project/core_app/templates/core_app/about_us_template.html
{% extends 'core_app/base_template.html' %}
{% load i18n %}

{% block main_center_card %}
  <h1 class="card-header content-title">
    {% trans 'About us' %}
  </h1>
  <div class="card-body">
    {#    <p>#}
    {#      {% trans 'Contact information' %}:#}
    {#    </p>#}
    <ul>
      <li>
        {% trans 'Author' %}: Lysov Viacheslav
      </li>
      <li>
        {% trans 'Email' %}: entsllor@gmail.com
      </li>
      {#      <li>#}
      {#        {% trans 'Phone number' %}: Your Phone Number#}
      {#      </li>#}
      {#      <li>#}
      {#        {% trans 'Address' %}: Put Your Address Here#}
      {#      </li>#}
    </ul>
  </div>
{% endblock %}

project/core_app/templates/core_app/base_template.html
{% extends 'core_app/meta_base_template.html' %}
{% load static %}
{% load i18n %}

{% block header %}
  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-lg">
      <a class="navbar-brand text-wrap text-center" href="/">
        {% block logo %}
          <img src="{% static 'core_app/logo.svg' %}" width="30" alt="icon">
        {% endblock %}
        {% block navbar_title %}
          <span id="navbar-title" class="navbar-title"></span>
        {% endblock %}
      </a>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'accounts:profile' %}">
            {% trans "Profile" %}
            <i class="bi bi-person-circle"></i>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'market_app:cart' %}">
            {% trans "Cart" %}
            <i class="bi bi-cart"></i>
          </a>
        </li>
      </ul>
    </div>
  </nav>

{% endblock %}
{% block main %}

  <div style="background-color: #dedede">
    <div class="container-lg min-vh-100 px-0 px-md-2">

      {% block main_container %}
        <div class="row g-0 g-md-2">
          <div class="col-md-2 order-0">
            {% block main_left_block %}
              {#       WARNING! DON'T MAKE SPACE BETWEEN CARD DIV ELSE DIV WILL BE NOT EMPTY       #}
              <div class="card my-2 border-0 sticky-top">{% block main_left_card %}{% endblock %}</div>
            {% endblock main_left_block %}
          </div>
          <div class="col-md-8 order-2 order-md-1">
            {% block messages %}
              {% include 'core_app/messages_block.html' %}
            {% endblock %}
            {% block main_center_block %}
              {#       WARNING! DON'T MAKE SPACE BETWEEN CARD DIV ELSE DIV WILL BE NOT EMPTY       #}
              <div class="card my-2 border-0">{% block main_center_card %}{% endblock %}</div>
            {% endblock main_center_block %}
          </div>

          <div class="col-md-2 order-1 order-md-2">
            {% block main_right_block %}
              {#       WARNING! DON'T MAKE SPACE BETWEEN CARD DIV ELSE DIV WILL BE NOT EMPTY       #}
              <div class="card my-2 border-0">{% block main_right_card %}{% endblock %}</div>
            {% endblock main_right_block %}
          </div>
        </div>
      {% endblock main_container %}
      <br>
    </div>
  </div>
{% endblock %}

{% block footer %}
  <div class="container p-1">

    <section>
      <form action="{% url 'set_language' %}" method="post" name="set_language_form">
        {% csrf_token %}
        <input name="next" type="hidden" value="{{ redirect_to }}">
        <label> {% trans 'Choose your language' %}
          <select name="language" class='form-select' onchange="document.forms.set_language_form.submit()">
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
              <option value="{{ language.code }}"{% if language.code == CURRENT_LANGUAGE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
              </option>
            {% endfor %}
          </select>
        </label>
        {#    set if need to display submit button    #}
        {#    <input type="submit" value="{% trans '' %}" style="display: inline">    #}
      </form>
    </section>

    <div class="text-center p-1">
      <a href="{% url 'core_app:about_us' %}" class="link-light">
        {% trans 'About us' %}
      </a>
    </div>
  </div>

  <script>
      const setNavbarTitleText = (text) => {
          text = typeof text !== "undefined" ? text : document.title;
          let navbarTitle = document.getElementById("navbar-title");
          if (navbarTitle) navbarTitle.textContent = text;
      }
      setNavbarTitleText()
  </script>
{% endblock %}

project/core_app/templates/core_app/form_page.html
{% extends 'core_app/meta_base_template.html' %}
{% load static %}
{% load i18n %}

{% block body %}
  <section class="min-vh-100 bg-secondary">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-sm-12 col-md-8 col-lg-6 col-xl-5">
          <div class="card mb-3 border-dark">
            <h3 class="card-header text-center text-light bg-dark">
              {% block page_title %}
              {% endblock %}
            </h3>
            <div class="card-body">

              {% block form_block %}
              {% endblock %}
            </div>
          </div>

        </div>
      </div>
    </div>
  </section>

{% endblock %}

project/core_app/templates/core_app/messages_block.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-dismissible fade show my-2
    {#  choose message-block color  #}
    {% if message.level <= 10 %}
      alert-secondary
    {% elif message.level <= 20 %}
      alert-info
    {% elif message.level <= 25 %}
      alert-success
    {% elif message.level <= 30 %}
      alert-warning
    {% else %}
      alert-danger
    {% endif %}" role="alert">
      {#   Possible needs to display tags and tags l10n   #}
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}

{% endif %}

project/core_app/templates/core_app/meta_base_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load i18n %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link rel="icon" href="{% static 'core_app/favicon.ico' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="{% static 'core_app/stylesheet.css' %}" type="text/css">
  <title>
    {% block title %}
      Pyllor
    {% endblock title %}
  </title>
  {% block extra_head %}
  {% endblock extra_head %}
</head>
<body>

{% block body %}
  <header>
    {% block header %}
    {% endblock header %}
  </header>


  <main role="main">
    {% block main %}
    {% endblock main %}
  </main>

  <footer class="bg-dark text-center text-white">
    {% block footer %}
    {% endblock footer %}
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
          crossorigin="anonymous"></script>{% endblock %}

</body>

</html>