project/market_app/api/urls.py
from rest_framework.routers import DefaultRouter

from market_app.api.views import (
    ProductViewSet, MarketViewSet, ProductTypeViewSet,
    ProductCategoryViewSet, OrderViewSet, OrderItemViewSet, OperationViewSet,
    BalanceViewSet, CartViewSet, CouponViewSet, UserViewSet,
)

app_name = "market-api"

router = DefaultRouter()
router.register("products", ProductViewSet)
router.register("markets", MarketViewSet)
router.register("product-categories", ProductCategoryViewSet)
router.register("product-types", ProductTypeViewSet)
router.register("order-items", OrderItemViewSet)
router.register("operations", OperationViewSet)
router.register("balances", BalanceViewSet)
router.register("coupons", CouponViewSet)
router.register("orders", OrderViewSet)
router.register("users", UserViewSet)
router.register("carts", CartViewSet)

urlpatterns = router.urls

project/market_app/urls.py
from django.urls import path
from . import views

app_name = 'market_app'
urlpatterns = [
    path('product/<int:pk>', views.ProductView.as_view(), name='product'),
    path('', views.CatalogueView.as_view(), name='catalogue'),
    path('create_product/', views.ProductCreateView.as_view(), name='create_product'),
    path('edit_product/<int:pk>', views.ProductEditView.as_view(), name='edit_product'),
    path('create_type/product/<int:pk>', views.ProductTypeCreate.as_view(), name='create_type'),
    path('edit_type/<int:pk>', views.ProductTypeEdit.as_view(), name='edit_type'),
    path('create_market/', views.MarketCreateView.as_view(), name='create_market'),
    path('edit_market/<int:pk>', views.MarketEditView.as_view(), name='edit_market'),
    path('my_cart/', views.CartView.as_view(), name='cart'),
    path('market/shipping/<int:pk>', views.ShippingPage.as_view(), name='shipping'),
    path('markets/', views.MarketsList.as_view(), name='market_list'),
    path('my_market/', views.UserMarketView.as_view(), name='user_market'),
    path('market/<int:pk>', views.MarketView.as_view(), name='market'),
    path('check_out/<int:pk>', views.CheckOutView.as_view(), name='checkout'),
    path('top_up', views.TopUpView.as_view(), name='top_up'),
    path('paying/<int:pk>', views.PayingView.as_view(), name='paying'),
    path('order_confirmation/', views.OrderConfirmationView.as_view(), name='order_confirmation'),
    path('search/', views.SearchProducts.as_view(), name='search_products'),
    path('operations/', views.OperationHistoryView.as_view(), name='operation_history'),
    path('order/<int:pk>', views.OrderDetail.as_view(), name='order_detail'),
    path('order/cancel/<int:pk>', views.cancel_order_view, name='order_cancel'),
    path('orders/', views.OrderListView.as_view(), name='orders'),
    path('coupons/my', views.UserCouponListView.as_view(), name='user_coupons')
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('site/', include('core_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('market_app.urls')),
    path('api/', include('market_app.api.urls', namespace="market-api")),
]

urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
urlpatterns.extend(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

if settings.DEBUG:
    import debug_toolbar

    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

project/market_app/models.py
from decimal import Decimal
from enum import Enum
from typing import Iterable, Union

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import F, QuerySet, Sum
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from market_app.validators import default_image_format_validator, product_image_size_validator, \
    market_logo_size_validator, product_attributes_symbols_validator, product_type_property_symbols_validator

User: User = get_user_model()
MAX_PRODUCT_PRICE_DIGITS_COUNT = settings.MAX_PRODUCT_PRICE_DIGITS_COUNT
MAX_BALANCE_DIGITS_COUNT = settings.MAX_BALANCE_DIGITS_COUNT
MONEY_DECIMAL_PLACES = settings.MONEY_DECIMAL_PLACES
MONEY_DECIMAL_QUANTIZE = Decimal('1.' + '0' * MONEY_DECIMAL_PLACES)
MAX_OPERATION_DIGITS_COUNT = MAX_BALANCE_DIGITS_COUNT
Money = Union[Decimal, int]


def validate_natural_number(number) -> None:
    if not isinstance(number, int) or number < 0:
        raise ValueError(f'Expected a natural number, got {number} instead')


class OrderStatusChoices(Enum):
    UNPAID = _("awaiting for payment")
    CANCELED = _("canceled")
    HAS_PAID = _("has successfully paid")
    SHIPPED = _("Shipped")
    DELIVERED = _("successfully completed")


class ProductCategory(models.Model):
    name = models.CharField(verbose_name=_('category'), max_length=63, unique=True)

    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    def __str__(self):
        return self.name


class Market(models.Model):
    owner = models.OneToOneField(
        to=User,
        on_delete=models.CASCADE,
        related_name='market',
        verbose_name=_('market owner')
    )
    name = models.CharField(verbose_name=_('name'), max_length=63, unique=True)
    description = models.TextField(verbose_name=_('description'), blank=True)
    created_at = models.DateTimeField(verbose_name=_('created at'), auto_now_add=True)
    logo = models.ImageField(
        verbose_name=_('logo'),
        null=True,
        blank=True,
        upload_to='markets_logos/',
        validators=[default_image_format_validator, market_logo_size_validator]
    )

    class Meta:
        verbose_name = _('market')
        verbose_name_plural = _('markets')

    def get_img_url(self):
        if self.logo and hasattr(self.logo, 'url'):
            return self.logo.url
        else:
            # return default img
            return settings.STATIC_URL + 'market_app/img/no_image.png'

    def get_absolute_url(self):
        return reverse_lazy('market_app:market', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(verbose_name=_('name'), max_length=63)
    description = models.TextField(verbose_name=_('description'), blank=True)
    market = models.ForeignKey(Market, verbose_name=_('market'), on_delete=models.CASCADE)
    original_price = models.DecimalField(
        verbose_name=_('price'),
        max_digits=MAX_PRODUCT_PRICE_DIGITS_COUNT,
        decimal_places=MONEY_DECIMAL_PLACES)
    discount_percent = models.DecimalField(
        verbose_name=_('discount percent'),
        max_digits=5,
        decimal_places=2,
        default=0,
        blank=True
    )
    attributes = models.TextField(
        verbose_name=_('attributes'),
        blank=True,
        validators=[product_attributes_symbols_validator]
    )
    created_at = models.DateTimeField(verbose_name=_('created at'), auto_now_add=True)
    available = models.BooleanField(verbose_name=_('available'), default=True)
    image = models.ImageField(
        verbose_name=_('image'),
        null=True,
        blank=True,
        upload_to='product_images/',
        validators=[default_image_format_validator, product_image_size_validator]
    )

    category = models.ForeignKey(
        'ProductCategory',
        verbose_name=_('category'),
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )

    def get_img_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            # return default img
            return settings.STATIC_URL + 'market_app/img/no_image.png'

    class Meta:
        verbose_name = _('product')
        verbose_name_plural = _('products')

    def __str__(self):
        return self.name

    @property
    def attributes_as_list(self) -> Iterable:
        return map(str.strip, self.attributes.split('\n'))

    def get_types(self) -> QuerySet['ProductType']:
        return getattr(self, 'product_types')

    @property
    def sale_price(self) -> Money:
        return round(self.original_price * ((100 - self.discount_percent) / 100), MONEY_DECIMAL_PLACES)

    @property
    def is_available_to_buy(self) -> bool:
        return self.available and self.get_types().filter(units_count__gt=0).exists()

    def create_product_type(self, properties=None, markup_percent=0, units_count=0) -> 'ProductType':
        product_type = ProductType.objects.create(
            product=self,
            markup_percent=markup_percent,
            units_count=units_count
        )
        if properties:
            product_type.properties = properties
        return product_type

    def get_absolute_url(self):
        return reverse_lazy('market_app:product', kwargs={'pk': self.pk})


class ProductType(models.Model):
    product = models.ForeignKey(
        Product,
        verbose_name=_('product'),
        related_name='product_types',
        on_delete=models.CASCADE
    )
    units_count = models.PositiveIntegerField(
        verbose_name=_('Amount'),
        blank=True,
        default=0
    )
    properties = models.JSONField(
        verbose_name=_('properties'),
        blank=True,
        default=dict,
        validators=[product_type_property_symbols_validator]
    )
    markup_percent = models.DecimalField(
        verbose_name=_('markup percent'),
        decimal_places=2,
        max_digits=5,
        blank=True,
        default=0
    )

    @property
    def original_price(self) -> Money:
        return round(self.product.original_price * (1 + (self.markup_percent / 100)), MONEY_DECIMAL_PLACES)

    @property
    def sale_price(self) -> Money:
        return round(self.product.sale_price * (1 + (self.markup_percent / 100)), MONEY_DECIMAL_PLACES)

    @property
    def has_units(self) -> bool:
        return self.units_count > 0

    def create_product_units(self, quantity: int) -> bool:
        status_code = ProductType.objects.filter(pk=self.pk).update(units_count=F('units_count') + quantity)
        return bool(status_code)

    def remove_product_units(self, quantity: int) -> bool:
        if self.units_count < quantity:
            raise ValueError(f"Can't remove {quantity} units. Current number of units: {self.units_count}")
        status_code = ProductType.objects.filter(pk=self.pk).update(units_count=F('units_count') - quantity)
        return bool(status_code)

    def take_units(self, expected_count: int, raise_exc_when_expected_count_gt_real_count=False) -> int:
        """
        Decrease product_type units count by expected count
        and return count of taken units.
        Set raise_exc_when_expected_count_gt_real_count=True if it's necessary to raise error
        when real product type units count is smaller than expected count to take.
        """
        real_count = self.units_count
        if expected_count < 1:
            return 0
        elif real_count < expected_count:
            if raise_exc_when_expected_count_gt_real_count:
                raise ValueError(f"Cannot take {expected_count} there are only {real_count}")
            taken_units = real_count
        else:
            taken_units = expected_count
        self.remove_product_units(taken_units)
        return taken_units

    @property
    def properties_as_str(self) -> str:
        return ', '.join(f'{key}: {value}' for key, value in self.properties.items() if value)

    @property
    def properties_as_dict(self) -> dict:
        return {attr: value for attr, value in self.properties.items()}

    def __str__(self):
        return f'{self.properties_as_str or f"id={self.id}"}'

    class Meta:
        verbose_name = _('Product type')
        verbose_name_plural = _('Product types')


class Cart(models.Model):
    _default_cart_value = dict
    max_product_type_count_on_cart = 20
    user = models.OneToOneField(
        to=User,
        verbose_name=_('user'),
        related_name='cart',
        on_delete=models.CASCADE
    )
    items = models.JSONField(verbose_name=_('items'), default=_default_cart_value)

    class Meta:
        verbose_name = _('cart')
        verbose_name_plural = _('carts')

    def get_cart_items(self) -> QuerySet[ProductType]:
        items = ProductType.objects.filter(id__in=self.items.keys()).select_related('product').only(
            'properties', 'markup_percent', 'units_count',
            'product__name', 'product__market_id',
            'product__discount_percent', 'product__original_price'
        )
        return items

    def get_count(self, pk) -> int:
        return self.items[str(pk)]

    def get_types_pks(self) -> tuple:
        return tuple(self.items.keys())

    def set_item(self, product_type_pk, quantity: int, commit: bool = True) -> None:
        validate_natural_number(quantity)
        product_type_pk = str(product_type_pk)
        if quantity == 0:
            if product_type_pk in self.items:
                del self.items[product_type_pk]
        else:
            self.items[product_type_pk] = quantity
        if commit:
            self.save(update_fields=['items'])

    def clear(self) -> int:
        return Cart.objects.filter(pk=self.pk).update(items=self._default_cart_value())

project/market_app/api/views.py
from rest_framework import viewsets

from market_app.api.serializers import *


class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.filter().order_by()
    serializer_class = ProductSerializer


class MarketViewSet(viewsets.ModelViewSet):
    queryset = Market.objects.all().order_by("-created_at")
    serializer_class = MarketSerializer


class ProductTypeViewSet(viewsets.ModelViewSet):
    queryset = ProductType.objects.filter().order_by()
    serializer_class = ProductTypeSerializer


class ProductCategoryViewSet(viewsets.ModelViewSet):
    queryset = ProductCategory.objects.filter().order_by()
    serializer_class = ProductCategorySerializer


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.filter().order_by()
    serializer_class = OrderSerializer


class OrderItemViewSet(viewsets.ModelViewSet):
    queryset = OrderItem.objects.filter().order_by()
    serializer_class = OrderItemSerializer


class OperationViewSet(viewsets.ModelViewSet):
    queryset = Operation.objects.filter().order_by()
    serializer_class = OperationSerializer


class BalanceViewSet(viewsets.ModelViewSet):
    queryset = Balance.objects.filter().order_by()
    serializer_class = BalanceSerializer


class CartViewSet(viewsets.ModelViewSet):
    queryset = Cart.objects.filter().order_by()
    serializer_class = CartSerializer


class CouponViewSet(viewsets.ModelViewSet):
    queryset = Coupon.objects.filter().order_by()
    serializer_class = CouponSerializer


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.filter().order_by()
    serializer_class = UserSerializer

project/market_app/templates/market_app/cart_page.html
{% extends 'market_app/app_base.html' %}
{% load i18n %}
{% load l10n %}
{% load currencies %}
{% load market_app_blocks %}
{% load market_app_utils %}
{% block title %}
  {% trans "My cart" %}
{% endblock %}

{% block main_center_block %}
  {% if cart.items %}
    <div class="card card-block">
      <h1 class="card-header content-title">
        {% trans 'My cart' %}
      </h1>

      <form action="{% url 'market_app:cart' %}" method="post">
        {% csrf_token %}
        <ul class="list-group list-group-flush">
          <script>
              const LOCAL_CURRENCY_RATE = Number("{{ LOCAL_CURRENCY.rate|unlocalize }}");
              const LOCAL_CURRENCY_SYM = "{{ LOCAL_CURRENCY.sym }}";
              let prices = {}
              let original_prices = {}

              const toLocalCurrency = price => {
                  let local_price = (price * LOCAL_CURRENCY_RATE).toFixed(2)
                  return String(local_price) + LOCAL_CURRENCY_SYM
              };

              const updateTotalPriceElem = (itemId) => {
                  let inputCountElem = document.getElementById("id_" + itemId)
                  let itemUnitCount = inputCountElem.value;
                  if (inputCountElem.value < 0) {
                      inputCountElem.value = 0;
                      itemUnitCount = 0;
                  }
                  let itemSalePrice = prices[itemId]
                  let itemOriginalPrice = original_prices[itemId]
                  let totalItemPriceElem = document.getElementById("itemTotalPrice" + itemId);
                  let totalSalePrice = itemUnitCount * itemSalePrice;
                  let totalOriginalPrice = itemUnitCount * itemOriginalPrice;
                  if (itemOriginalPrice !== itemSalePrice) {
                      let totalItemOriginalPriceElem = document.getElementById("itemTotalOriginalPrice" + itemId);
                      if (itemUnitCount < 1) {
                          totalItemOriginalPriceElem.textContent = "";
                      } else {
                          totalItemOriginalPriceElem.textContent = toLocalCurrency(totalOriginalPrice);
                      }
                  }
                  totalItemPriceElem.textContent = toLocalCurrency(totalSalePrice);
                  return totalSalePrice
              }

              const onChangeCount = () => {
                  let totalPrice = 0
                  for (let itemId in prices) {
                      totalPrice += updateTotalPriceElem(itemId);
                  }
                  document.getElementById('total_sale_price').textContent = toLocalCurrency(totalPrice)
              };
              window.onload = onChangeCount
          </script>
          {% for item in cart.get_cart_items %}
            {% with item.pk as pk %}
              <script>
                  prices[{{ pk }}] = {{ item.sale_price }};
                  original_prices[{{ pk }}] = {{ item.original_price }};
              </script>
              <li class="list-group-item">
                <a href="{% url 'market_app:product' pk=item.product_id %}">
                  <h3>{{ item.product.name }}</h3>
                </a>
                {% for attr, value in item.properties_as_dict.items %}
                  {{ attr }}: {{ value }} <br>
                {% endfor %}
                <div>
                  {% trans 'Unit price' %}:
                  <b>
                    {% to_local_currency item.sale_price %}
                  </b> <br>
                  <label for="id_{{ pk }}">
                    {% trans 'Amount' %}:
                  </label>
                  <input id="id_{{ pk }}" name="{{ pk }}" type="number" class="form-control"
                         value="{% units_in_cart_count cart pk=pk %}" onchange="onChangeCount()">
                </div>
                <p>
                  {% trans 'Total order item price' %}:
                  <span id="itemTotalPrice{{ pk }}" class="text-success">
                    {% to_local_currency item.sale_price %}
                  </span>
                  {% if item.product.discount_percent %}
                    <s id="itemTotalOriginalPrice{{ pk }}" class="text-secondary">
                      {% to_local_currency item.product.original_price %}
                    </s>
                  {% endif %}
                  <br>
                </p>
              </li>
            {% endwith %}
          {% endfor %}
        </ul>
        <div class="card-body">
          <p>
            {% trans "Total order price" %}:
            <b id="total_sale_price" class="text-success"></b>
          </p>
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-primary d-block ms-auto">
            {% trans 'Submit' %}
          </button>
        </div>
      </form>

    </div>
  {% else %}
    <div class="display-5">
      {% trans 'Your cart is empty' %}
    </div>
    {% if products %}
      <div class="display-6">
        {% trans 'But these products will interest you' %}
      </div>
      {% products_catalogue limit=12 %}
    {% endif %}
  {% endif %}
{% endblock %}

project/market_app/templates/market_app/checkout_page.html
{% extends 'market_app/app_base.html' %}
{% load i18n %}
{% load l10n %}
{% load currencies %}

{% block title %}{% trans "Order" %}{% endblock %}

{% block main_center_block %}
  <div class="card card-block">
    <h1 class="card-header content-title">
      {% trans 'Check out' %}
    </h1>
    <ul class="list-group list-group-flush">
      {% for order_item in order.items.all %}
        <li class="list-group-item">
          <h4 class="text-center">
            <a href="{{ order_item.product_type.product.get_absolute_url }}">
              {{ order_item.product_type.product.name }}
            </a>
          </h4>
          {% trans "Amount" %}:
          <b>
            {{ order_item.amount }}
          </b>
          <br class="p">
          {% for prop, value in order_item.product_type.properties_as_dict.items %}
            {{ prop }}: {{ value }}<br>
          {% endfor %}
          {% trans 'Sale price' %}:
          <span class="text-success">
            {% to_local_currency order_item.total_price %}
          </span>
          <br>
        </li>
      {% endfor %}
    </ul>
    <div class="card-body">

      <p>
        {% if user.balance.amount %}
          {% trans "Your balance" %}: {% to_local_currency user.balance.amount %} <br>
        {% endif %}
        {% trans 'Order price' %}:
        <b class="text-success">
          {% to_local_currency total_price_without_coupon_discount %}
        </b>
      </p>
      <div id="coupon_discount_block" style="display: none">
        <p class="text-success mb-0">
          {% trans 'Coupon discount' %}: <span id="coupon_discount_amount"></span>
        </p>
        <p class="fw-bold">
          {% trans 'Total price' %} <span id="total_order_price"></span>
        </p>
      </div>
      <form method="post" name="check_out" action="{% url 'market_app:checkout' pk=order.pk %}">
        {% include 'core_app/include/pretty_form.html' with form=form %}
        {% csrf_token %}
      </form>
    </div>
  </div>
  <script>
      const TOTAL_ORDER_PRICE = "{{ total_price_without_coupon_discount|unlocalize }}"
      const LOCAL_CURRENCY_RATE = Number("{{ LOCAL_CURRENCY.rate|unlocalize }}");
      const LOCAL_CURRENCY_SYM = "{{ LOCAL_CURRENCY.sym }}";
      const coupons = JSON.parse('{{ form.coupons_json }}'.replace(/&quot;/ig, '"'))
      const totalOrderPriceElem = document.getElementById('total_order_price')
      const couponChoiceForm = document.getElementById('id_coupon')
      const couponDiscountBlock = document.getElementById('coupon_discount_block')
      const couponDiscountAmount = document.getElementById('coupon_discount_amount')
      const discountLimitFormat = "{{ form.discount_limit_format }}"

      const toLocalCurrency = price => {
          let local_price = (price * LOCAL_CURRENCY_RATE).toFixed(2)
          return String(local_price) + LOCAL_CURRENCY_SYM
      };

      const localizeCouponChoicesText = () => {
          let couponChoices = couponChoiceForm.options;
          for (let couponChoice of couponChoices) {
              let discount_limit = coupons[couponChoice.value]['discount_limit']
              if (discount_limit) {
                  discount_limit = toLocalCurrency(discount_limit)
                  couponChoice.textContent += ' ' + discountLimitFormat.replace('{discount_limit}', discount_limit)
              }
          }
      }

      const getCouponDiscount = (coupon, price) => {
          let discountAmount = price * coupon['discount_percent'] / 100;
          if (coupon['discount_limit']) {
              discountAmount = Math.min(discountAmount, coupon['discount_limit']);
          }
          return discountAmount
      }

      const onChangeActivatedCoupon = () => {
          if (couponChoiceForm.value) {
              let coupon = coupons[couponChoiceForm.value];
              let discountAmount = getCouponDiscount(coupon, TOTAL_ORDER_PRICE);
              let totalPrice = TOTAL_ORDER_PRICE - discountAmount;
              couponDiscountBlock.style.display = 'block';
              totalOrderPriceElem.textContent = toLocalCurrency(totalPrice);
              couponDiscountAmount.textContent = toLocalCurrency(discountAmount);
          } else {
              totalOrderPriceElem.textContent = toLocalCurrency(TOTAL_ORDER_PRICE);
              couponDiscountBlock.style.display = 'none';
          }
      }

      const onloadPage = () => {
          onChangeActivatedCoupon();
          localizeCouponChoicesText();
      }

      onload = onloadPage
  </script>
{% endblock %}

project/market_app/templates/market_app/create_product.html
{% extends 'market_app/form_block.html' %}
{% load i18n %}

{% block title %}{% trans "Create product" %}{% endblock %}
{% block card-title %}{% trans 'Create product' %}{% endblock %}

{% block form_block %}
  <form action="{% url 'market_app:create_product' %}" method="post">
    {% include 'core_app/include/pretty_form.html' with form=form %}
    {% csrf_token %}
  </form>
{% endblock %}

project/market_app/templates/market_app/market_create.html
{% extends 'market_app/form_block.html' %}
{% load i18n %}

{% block title %}{% trans "Create market" %}{% endblock %}
{% block card-title %}{% trans "Create market" %}{% endblock %}

{% block form_block %}
  <form action="{% url 'market_app:create_market' %}" method="post" enctype="multipart/form-data">
    {% include 'core_app/include/pretty_form.html' with form=form %}
    {% csrf_token %}
  </form>
{% endblock %}

project/market_app/templates/market_app/market_edit.html
{% extends 'market_app/form_block.html' %}
{% load i18n %}

{% block title %}{% trans "Market edit" %}{% endblock %}
{% block card-title %}{% trans 'Market edit' %}{% endblock %}

{% block form_block %}
  <form action="{% url 'market_app:edit_market' pk=view.kwargs.pk %}" method="post" enctype="multipart/form-data">
    {% include 'core_app/include/pretty_form.html' with form=form without_button=True %}
    {% csrf_token %}
    <div class="d-flex justify-content-end gap-1">
      <a href="{{ market.get_absolute_url }}"
      class="btn btn-danger ms-1">{% trans 'Cancel' %}</a>
      <button type="submit" class="btn btn-primary">
        {% trans 'Submit' %}
      </button>
    </div>
  </form>
{% endblock %}

project/market_app/templates/market_app/markets_list.html
{% extends 'market_app/app_base.html' %}
{% load i18n %}
{% load cache %}

{% block title %}{% trans "Markets" %}{% endblock %}

{% block main_center_block %}
  {% cache 600 market_list CURRENT_LANGUAGE page_obj.number %}
  <div class="row row-cols-2 row-cols-md-3 g-2 m-0">
    {% for market in markets %}
      <div class="col">
        <a class="text-decoration-none text-dark" href="{{ market.get_absolute_url }}">
          <div class="card h-100">
            <img class="card-img-top" style="height: 100%; object-fit: cover"
                 src="{{ market.get_img_url }}" alt="market logo">
            <div class="card-footer">
              {{ market.name }}
              <p class="card-text">{% trans 'Products count' %}: {{ market.product_set.count }}</p>
            </div>
          </div>
        </a>
      </div>
    {% empty %}
      <div class="display-5 w-100 text-center">
        {% trans "There are no markets" %}.
      </div>
    {% endfor %}
  </div>
  {% include 'market_app/include/paginator.html' %}
  {% endcache %}
{% endblock %}

project/market_app/templates/market_app/top_up_page.html
{% extends 'core_app/form_page.html' %}
{% load i18n %}

{% block title %}{% trans "Top up" %}{% endblock %}

{% block page_title %}
  {% trans 'Top up' %}
{% endblock %}

{% block form_block %}
  <form action="{% url 'market_app:top_up' %}" method="post">
    {% include 'core_app/include/pretty_form.html' with form=form %}
    {% csrf_token %}
  </form>
{% endblock %}

project/market_app/templates/market_app/user_market.html
{% extends 'market_app/app_base.html' %}
{% load i18n %}
{% load market_app_blocks %}

{% block title %}{% trans "My market" %}{% endblock %}

{% block main_center_block %}
  <div class="card card-block">
    <h1 class="card-header content-title">
      {{ market.name }}
    </h1>

    <div class="card-body">
      <div class="row">
        <div class="col col-12 col-md-6">
          {% trans 'Product count' %}: {{ products|length }}
        </div>
        <div class="col col-12 col-md-6 d-flex justify-content-center justify-content-md-end">
          <img class="img-fluid"
               src="{{ market.get_img_url }}"
               alt="market logo">
        </div>
      </div>
    </div>
    <div class="card-footer">
      <div class="d-flex flex-wrap justify-content-end gap-1">
        <a href="{% url 'market_app:edit_market' pk=market.pk %}"
           class="btn btn-primary" role="button">{% trans 'Edit market' %}</a>
        <a href="{% url 'market_app:shipping' pk=market.pk %}"
           class="btn btn-primary" role="button">{% trans 'Shipping' %}</a>
        <a href="{% url 'market_app:create_product' %}"
           class="btn btn-primary" role="button">{% trans 'Create Product' %}</a>
        <a href="{{ market.get_absolute_url }}"
           class="btn btn-primary" role="button">{% trans 'Public Page' %}</a>
      </div>
    </div>
  </div>

  {% products_catalogue products page_size=36 %}
{% endblock %}